version: 2.1

orbs:
  puppeteer: threetreeslight/puppeteer@0.1.2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest
      environment:
        NODE_ENV: development

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-averjs-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-averjs-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/
          paths:
            - repo
  
  build: 
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn build
  
  lint: 
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint
  
  test: 
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn test

workflows:
  version: 2.1
  test:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - puppeteer/test:
          requires:
            - install