version: '2'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
    volumes:
      - /data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null --auth

  redis:
    image: registry.ppm-vi.de/docker/redis:latest
    volumes:
      - /data
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=